### ISSUE TITLE
ValueError: Expected parameter loc (Tensor of shape (32880, 12)) of distribution Normal(loc: torch.Size([32880, 12]), scale: torch.Size([32880, 12])) to satisfy the constraint Real(), but found invalid values:

### ISSUE THREAD

**Issue by COST-97** [Alescontrela/AMP_for_hardware#1] opened 2022-04-10 01:13 UTC
**Describe the bug**
'ValueError: Expected parameter loc (Tensor of shape (32880, 12)) of distribution Normal(loc: torch.Size([32880, 12]), scale: torch.Size([32880, 12])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0',
       grad_fn=<AddmmBackward0>)`

**To Reproduce**
    Execute `python legged_gym/scripts/train.py --task=a1_amp`
    This error occurs.
    
**Expected behavior**
    The normal record and no bugs.

**System (please complete the following information):**
    Commit: [https://github.com/Alescontrela/AMP_for_hardware/commit/8f3b9caa6376b81b36d5242c45a297f79ee5348c](url)
    OS: Ubuntu 18.04
    GPU: GeForce GTX 1080 Ti
    CUDA: 11.1
    GPU Driver:  510.47.03

**Comment by Alescontrela** [comment] 2022-04-10 01:16
Are you running this with the default data, or are you using your own reference data?

**Comment by COST-97** [comment] 2022-04-10 01:19
The default data.

**Comment by Alescontrela** [comment] 2022-04-10 01:33
ok, could you please fill out the bug report as described in the issue template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Execute `./path/script arg1 arg2`
1. Then ... 
1. See error: ...

**Expected behavior**
A clear and concise description of what you expected to happen.

**System (please complete the following information):**
 - Commit: [e.g. 8f3b9ca]
 - OS: [e.g. Ubuntu 20.04]
 - GPU: [e.g. RTX 2060 Super]
 - CUDA: [e.g. 11.4]
 - GPU Driver: [e.g. 470.82.01]

**Additional context**
Add any other context about the problem here.

**Comment by COST-97** [comment] 2022-04-13 03:39
Hello. Another important question is what is the range of the action space?
Specifically,  what is the range of the `actions_scaled` in `_compute_torques(self, actions)` function in `legged_robot.py`?

It seems that `clip_actions = 100.` in `legged_robot_config.py`, but it is too large.

**Comment by Alescontrela** [comment] 2022-04-19 01:53
Are you still experiencing the first issue you mentioned? the range of actions is between -3.14 and 3.14. In practice action clipping doesn't happen and is not necessary. This parameter is there just in case.

**Comment by COST-97** [comment] 2022-04-21 08:00
Hello. I am not currently running this program again. 
I copied the code with the AMP classifier and wanted to implement it in Pybullet(the SAC algorithm that I used). I find it difficult for policy to maximize both extrinsic and intrinsic rewards. And when the intrinsic reward large, the A1 robot tends to stand still and do nothing. Maybe the model converges to a local optimum, right?

**Comment by Alescontrela** [comment] 2022-04-27 21:23
Hi @COST-97, i'm not familiar with the setup you have descried so i'm not entirely sure. I assume you are training with much smaller batch sizes in PyBullet, which might have a negative impact on training. I initially implemented this project in PyBullet and found that I couldn't even optimize the discriminator objective.

Closing this issue for now as it's not related to the repo.

**Closed by Alescontrela** 2022-04-27 21:23 UTC
Labels: bug

**Comment by binfengxueqian** [comment] 2023-11-13 03:27
I encountered the same problem. When I trained using the author's motion data, everything was fine, but when I used the data I built myself, it reported the same error

> Loaded 55.22s. motion from datasets/mpc_motions/trot1.txt.
Preloading 2000000 transitions
Finished preloading
Traceback (most recent call last):
  File "legged_gym/scripts/train.py", line 47, in <module>
    train(args)
  File "legged_gym/scripts/train.py", line 43, in train
    ppo_runner.learn(num_learning_iterations=train_cfg.runner.max_iterations, init_at_random_ep_len=True)
  File "/home/coral/project/python_project/legged_gym_amp/AMP_for_hardware/rsl_rl/rsl_rl/runners/amp_on_policy_runner.py", line 132, in learn
    actions = self.alg.act(obs, critic_obs, amp_obs)
  File "/home/coral/project/python_project/legged_gym_amp/AMP_for_hardware/rsl_rl/rsl_rl/algorithms/amp_ppo.py", line 120, in act
    self.transition.actions = self.actor_critic.act(aug_obs).detach()
  File "/home/coral/project/python_project/legged_gym_amp/AMP_for_hardware/rsl_rl/rsl_rl/modules/actor_critic.py", line 128, in act
    self.update_distribution(observations)
  File "/home/coral/project/python_project/legged_gym_amp/AMP_for_hardware/rsl_rl/rsl_rl/modules/actor_critic.py", line 125, in update_distribution
    self.distribution = Normal(mean, mean*0. + std)
  File "/home/coral/miniconda3/envs/amp_hw/lib/python3.8/site-packages/torch/distributions/normal.py", line 56, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "/home/coral/miniconda3/envs/amp_hw/lib/python3.8/site-packages/torch/distributions/distribution.py", line 68, in __init__
    raise ValueError(
ValueError: Expected parameter loc (Tensor of shape (5480, 12)) of distribution Normal(loc: torch.Size([5480, 12]), scale: torch.Size([5480, 12])) to satisfy the constraint Real(), but found invalid values:
tensor([[-0.0372, -0.0302, -0.0185,  ...,  0.0144, -0.0826, -0.0736],
        [-0.0353, -0.0696, -0.0225,  ..., -0.0090, -0.0881, -0.0835],
        [-0.0239, -0.0414, -0.0223,  ...,  0.0260, -0.0804, -0.0669],
        ...,
        [-0.0259, -0.0594, -0.0475,  ...,  0.0638, -0.0836, -0.0820],
        [ 0.0023, -0.0835, -0.0189,  ...,  0.0250, -0.0752, -0.0603],
        [-0.0320, -0.0530, -0.0189,  ...,  0.0072, -0.0847, -0.0662]],
       device='cuda:0')

The error shows me that there is invalid data in the  tensor, but have I checked it

In addition, I ran 'replay_amp_data. py' using my own data, which can display normally. However, the joint angle of hip feels reversed, and I don't know if it's due to different coordinate systems or different leg order. The leg order in the motion data I provided is [FR, FL, RR, RL]

this is my dataset 
[trot1.txt](https://github.com/Alescontrela/AMP_for_hardware/files/13330467/trot1.txt)

**Comment by kc-ustc** [comment] 2023-12-18 08:06
> The error shows me that there is invalid data in the tensor, but have I checked it
> 
> In addition, I ran 'replay_amp_data. py' using my own data, which can display normally. However, the joint angle of hip feels reversed, and I don't know if it's due to different coordinate systems or different leg order. The leg order in the motion data I provided is [FR, FL, RR, RL]
have you solved this problem?

**Comment by kc-ustc** [comment] 2023-12-18 08:10
> I encountered the same problem. When I trained using the author's motion data, everything was fine, but when I used the data I built myself, it reported the same error
> 
> > Loaded 55.22s. motion from datasets/mpc_motions/trot1.txt.
> > Preloading 2000000 transitions
> > Finished preloading
> > Traceback (most recent call last):
> > File "legged_gym/scripts/train.py", line 47, in 
> > train(args)
> > File "legged_gym/scripts/train.py", line 43, in train
> > ppo_runner.learn(num_learning_iterations=train_cfg.runner.max_iterations, init_at_random_ep_len=True)
> > File "/home/coral/project/python_project/legged_gym_amp/AMP_for_hardware/rsl_rl/rsl_rl/runners/amp_on_policy_runner.py", line 132, in learn
> > actions = self.alg.act(obs, critic_obs, amp_obs)
> > File "/home/coral/project/python_project/legged_gym_amp/AMP_for_hardware/rsl_rl/rsl_rl/algorithms/amp_ppo.py", line 120, in act
> > self.transition.actions = self.actor_critic.act(aug_obs).detach()
> > File "/home/coral/project/python_project/legged_gym_amp/AMP_for_hardware/rsl_rl/rsl_rl/modules/actor_critic.py", line 128, in act
> > self.update_distribution(observations)
> > File "/home/coral/project/python_project/legged_gym_amp/AMP_for_hardware/rsl_rl/rsl_rl/modules/actor_critic.py", line 125, in update_distribution
> > self.distribution = Normal(mean, mean*0. + std)
> > File "/home/coral/miniconda3/envs/amp_hw/lib/python3.8/site-packages/torch/distributions/normal.py", line 56, in **init**
> > super().**init**(batch_shape, validate_args=validate_args)
> > File "/home/coral/miniconda3/envs/amp_hw/lib/python3.8/site-packages/torch/distributions/distribution.py", line 68, in **init**
> > raise ValueError(
> > ValueError: Expected parameter loc (Tensor of shape (5480, 12)) of distribution Normal(loc: torch.Size([5480, 12]), scale: torch.Size([5480, 12])) to satisfy the constraint Real(), but found invalid values:
> > tensor([[-0.0372, -0.0302, -0.0185,  ...,  0.0144, -0.0826, -0.0736],
> > [-0.0353, -0.0696, -0.0225,  ..., -0.0090, -0.0881, -0.0835],
> > [-0.0239, -0.0414, -0.0223,  ...,  0.0260, -0.0804, -0.0669],
> > ...,
> > [-0.0259, -0.0594, -0.0475,  ...,  0.0638, -0.0836, -0.0820],
> > [ 0.0023, -0.0835, -0.0189,  ...,  0.0250, -0.0752, -0.0603],
> > [-0.0320, -0.0530, -0.0189,  ...,  0.0072, -0.0847, -0.0662]],
> > device='cuda:0')
> 
> The error shows me that there is invalid data in the tensor, but have I checked it
> 
> In addition, I ran 'replay_amp_data. py' using my own data, which can display normally. However, the joint angle of hip feels reversed, and I don't know if it's due to different coordinate systems or different leg order. The leg order in the motion data I provided is [FR, FL, RR, RL]
> 
> this is my dataset [trot1.txt](https://github.com/Alescontrela/AMP_for_hardware/files/13330467/trot1.txt)

have you solved this problem?I also met this problem

**Comment by apirrone** [comment] 2024-08-01 13:56
Hello, I have the same problem. 
It seems that all observations are nan only on certain environments 

![image](https://github.com/user-attachments/assets/16d822a3-a9d6-47f8-b058-a008a704c0c8)

Has anyone been able to solve this ? 

Thanks !

**Comment by apirrone** [comment] 2024-08-02 12:38
Found it. 

In domain randomization, there was : 

```python
added_mass_range = [-1.0, 1.0]
```

My robot is about 1Kg, so I guess in some of the envs, they had negative mass, or mass so small it caused instabilities :)

**Comment by chy2948331536** [comment] 2024-12-09 19:33
I fix this bug,in function:
def get_full_frame_at_time_batch(self, traj_idxs, times):
        p = times / self.trajectory_lens[traj_idxs]
        n = self.trajectory_num_frames[traj_idxs]
        idx_low, idx_high = np.floor(p * n).astype(np.int), np.ceil(p * n).astype(np.int)
        all_frame_pos_starts = torch.zeros(len(traj_idxs), AMPLoader.POS_SIZE, device=self.device)
        all_frame_pos_ends = torch.zeros(len(traj_idxs), AMPLoader.POS_SIZE, device=self.device)
        all_frame_rot_starts = torch.zeros(len(traj_idxs), AMPLoader.ROT_SIZE, device=self.device)
        all_frame_rot_ends = torch.zeros(len(traj_idxs), AMPLoader.ROT_SIZE, device=self.device)
        all_frame_amp_starts = torch.zeros(len(traj_idxs), AMPLoader.JOINT_VEL_END_IDX - AMPLoader.JOINT_POSE_START_IDX, device=self.device)
        all_frame_amp_ends = torch.zeros(len(traj_idxs),  AMPLoader.JOINT_VEL_END_IDX - AMPLoader.JOINT_POSE_START_IDX, device=self.device)
        for traj_idx in set(traj_idxs):
            trajectory = self.trajectories_full[traj_idx]
            traj_mask = traj_idxs == traj_idx
            all_frame_pos_starts[traj_mask] = AMPLoader.get_root_pos_batch(trajectory[idx_low[traj_mask]])
            all_frame_pos_ends[traj_mask] = AMPLoader.get_root_pos_batch(trajectory[idx_high[traj_mask]])
            all_frame_rot_starts[traj_mask] = AMPLoader.get_root_rot_batch(trajectory[idx_low[traj_mask]])
            all_frame_rot_ends[traj_mask] = AMPLoader.get_root_rot_batch(trajectory[idx_high[traj_mask]])
            all_frame_amp_starts[traj_mask] = trajectory[idx_low[traj_mask]][:, AMPLoader.JOINT_POSE_START_IDX:AMPLoader.JOINT_VEL_END_IDX]
            all_frame_amp_ends[traj_mask] = trajectory[idx_high[traj_mask]][:, AMPLoader.JOINT_POSE_START_IDX:AMPLoader.JOINT_VEL_END_IDX]
        blend = torch.tensor(p * n - idx_low, device=self.device, dtype=torch.float32).unsqueeze(-1)

        pos_blend = self.slerp(all_frame_pos_starts, all_frame_pos_ends, blend)
        **rot_blend = utils.quaternion_slerp(all_frame_rot_starts.clone(), all_frame_rot_ends.clone(), blend)**
        amp_blend = self.slerp(all_frame_amp_starts, all_frame_amp_ends, blend)
        return torch.cat([pos_blend, rot_blend, amp_blend], dim=-1)
        
**rot_blend = utils.quaternion_slerp(all_frame_rot_starts.clone(), all_frame_rot_ends.clone(), blend)**

def quaternion_slerp(q0, q1, fraction, spin=0, shortestpath=True):
    """Batch quaternion spherical linear interpolation."""

    out = torch.zeros_like(q0)

    zero_mask = torch.isclose(fraction, torch.zeros_like(fraction)).squeeze()
    ones_mask = torch.isclose(fraction, torch.ones_like(fraction)).squeeze()
    out[zero_mask] = q0[zero_mask]
    out[ones_mask] = q1[ones_mask]

    d = torch.sum(q0 * q1, dim=-1, keepdim=True)
    dist_mask = (torch.abs(torch.abs(d) - 1.0) < _EPS).squeeze()
    out[dist_mask] = q0[dist_mask]

    if shortestpath:
        d_old = torch.clone(d)
        d = torch.where(d_old < 0, -d, d)
        q1 = torch.where(d_old < 0, -q1, q1)

    angle = torch.acos(d) + spin * torch.pi
    angle_mask = (torch.abs(angle) < _EPS).squeeze() | torch.isnan(angle.squeeze())
    out[angle_mask] = q0[angle_mask]

    final_mask = torch.logical_or(zero_mask, ones_mask)
    final_mask = torch.logical_or(final_mask, dist_mask)
    final_mask = torch.logical_or(final_mask, angle_mask)
    final_mask = torch.logical_not(final_mask)

    isin = 1.0 / angle
    q0 *= torch.sin((1.0 - fraction) * angle) * isin
    q1 *= torch.sin(fraction * angle) * isin
    q0 += q1
    out[final_mask] = q0[final_mask]
    return out
    
    add | torch.isnan(angle.squeeze()) to angle_mask = (torch.abs(angle) < _EPS).squeeze() | torch.isnan(angle.squeeze())
    when d too close to 1,the torch.acos(d) will back nan
